name: WhatsApp Daily Countdown

on:
  schedule:
    # Menggunakan zona waktu UTC. Jam 17:00 UTC sama dengan jam 12 malam (00:00 WIB)
    - cron: '0 17 * * *'
  workflow_dispatch: # Memunculkan tombol "Run workflow" untuk tes manual

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # <--- Di sini sudah diganti ke versi 20

    - name: Install Dependencies
      run: npm install

    - name: Run Countdown Bot
      run: node bot.js
